title: Prashant Raghuwanshi # your name (or website title) here
logo: "/images/prashant_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Cloud Data Architect\Lead with 15+ years of experience in Recommending, developing & Implementing the enterprise-software solutions for Data Engineering, Analytics & Data Science related requirements.
  <br><br>
  Background includes E2E developments of solutions for Enterprise wide Cloud Data Integration, Migration, Real-time Analytics, Datalake, DataWarehouse, Master Data Management, Model development for Data Science, CICD Pipelines & Legacy system Modernization with excellent communication & technical skills.
  <br><br>
  Working Experience in Healthcare, Insurance, Manufacturing & Financial Business Domains.
  <br><br>
  <a href="https://www.linkedin.com/in/prashant-raghuwanshi-78945a33/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
